# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
- template: variables/build.yml  # Template reference

stages:
- stage: BuildStage
  displayName: Build stage

  jobs:
  - template: jobs/build.yml  # Template reference
    parameters:
      dockerRegistryServiceConnection: '$(dockerRegistryServiceConnection)'
      imageRepository: '$(imageRepository)'
      tag: '$(tag)'
      vmImageName: '$(vmImageName)'

- stage: TestStage
  displayName: Test deployment
  dependsOn: BuildStage

  jobs:
  - template: jobs/deploy-web.yml  # Template reference
    parameters:
      deploymentName: DeployTest
      webAppServiceConnection: '$(webAppServiceConnection)'
      containerRegistry: '$(containerRegistry)'
      imageRepository: '$(imageRepository)'
      tag: '$(tag)'
      webAppName: '$(webAppNameBase)-Test'
      environmentName: '$(webAppNameBase)-Test'

- stage: LoadTestStage
  displayName: Load test deployment
  dependsOn: TestStage

  jobs:
  - template: jobs/deploy-web.yml  # Template reference
    parameters:
      deploymentName: DeployTest
      webAppServiceConnection: '$(webAppServiceConnection)'
      containerRegistry: '$(containerRegistry)'
      imageRepository: '$(imageRepository)'
      tag: '$(tag)'
      webAppName: '$(webAppNameBase)-LoadTest'
      environmentName: '$(webAppNameBase)-LoadTest'

- stage: UATStage
  displayName: UAT deployment
  dependsOn: TestStage

  jobs:
  - template: jobs/deploy-web.yml  # Template reference
    parameters:
      deploymentName: DeployTest
      webAppServiceConnection: '$(webAppServiceConnection)'
      containerRegistry: '$(containerRegistry)'
      imageRepository: '$(imageRepository)'
      tag: '$(tag)'
      webAppName: '$(webAppNameBase)-UAT'
      environmentName: '$(webAppNameBase)-UAT'      

- stage: ProdStage
  displayName: Prod deployment
  dependsOn: LoadTestStage

  jobs:
  - template: jobs/deploy-web.yml  # Template reference
    parameters:
      deploymentName: DeployProd
      webAppServiceConnection: '$(webAppServiceConnection)'
      containerRegistry: '$(containerRegistry)'
      imageRepository: '$(imageRepository)'
      tag: '$(tag)'
      webAppName: '$(webAppNameBase)-Prod'
      environmentName: '$(webAppNameBase)-Prod'     