# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
- template: variables/build.yml  # Template reference

stages:
- stage: BuildStage
  displayName: Build stage

  jobs:
  - template: jobs/build.yml  # Template reference
    parameters:
      dockerRegistryServiceConnection: '$(dockerRegistryServiceConnection)'
      imageRepository: '$(imageRepository)'
      tag: '$(tag)'
      vmImageName: '$(vmImageName)'

- stage: TestStage
  displayName: Test deployment
  dependsOn: BuildStage

  variables:
    environmentName: '${{ variables.webAppNameBase }}-Test'

  jobs:
  - template: jobs/deploy-web.yml  # Template reference
    parameters:
      deploymentName: DeployTest
      webAppServiceConnection: '$(webAppServiceConnection)'
      containerRegistry: '$(containerRegistry)'
      imageRepository: '$(imageRepository)'
      tag: '$(tag)'
      webAppName: '$(environmentName)'
      environmentName: '$(environmentName)'

- stage: LoadTestStage
  displayName: Load test deployment
  dependsOn: TestStage

  variables:
    environmentName: '${{ variables.webAppNameBase }}-LoadTest'

  jobs:
  - template: jobs/deploy-web.yml  # Template reference
    parameters:
      deploymentName: DeployTest
      webAppServiceConnection: '$(webAppServiceConnection)'
      containerRegistry: '$(containerRegistry)'
      imageRepository: '$(imageRepository)'
      tag: '$(tag)'
      webAppName: '$(environmentName)'
      environmentName: '$(environmentName)'

- stage: UATStage
  displayName: UAT deployment
  dependsOn: TestStage

  variables:
    environmentName: '${{ variables.webAppNameBase }}-UAT'

  jobs:
  - template: jobs/deploy-web.yml  # Template reference
    parameters:
      deploymentName: DeployTest
      webAppServiceConnection: '$(webAppServiceConnection)'
      containerRegistry: '$(containerRegistry)'
      imageRepository: '$(imageRepository)'
      tag: '$(tag)'
      webAppName: '$(environmentName)'
      environmentName: '$(environmentName)'      

- stage: ProdStage
  displayName: Prod deployment
  dependsOn: LoadTestStage

  variables:
    environmentName: '${{ variables.webAppNameBase }}-Prod'

  jobs:
  - template: jobs/deploy-web.yml  # Template reference
    parameters:
      deploymentName: DeployProd
      webAppServiceConnection: '$(webAppServiceConnection)'
      containerRegistry: '$(containerRegistry)'
      imageRepository: '$(imageRepository)'
      tag: '$(tag)'
      webAppName: '$(environmentName)'
      environmentName: '$(environmentName)'     