# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  - template: variables/build.yml  # Template reference

stages:
- stage: BuildStage
  displayName: Build stage

  jobs:
  - template: jobs/build.yml  # Template reference
    parameters:
      dockerfilePath: '$(dockerfilePath)'
      dockerRegistryServiceConnection: '$(dockerRegistryServiceConnection)'
      imageRepository: '$(imageRepository)'
      tag: '$(tag)'
      vmImageName: '$(vmImageName)'

- stage: TestStage
  displayName: Test deployment
  dependsOn: BuildStage

  variables:
    deployEnvironmentName: '$(webAppNameBase)-Test'

  jobs:
  - template: jobs/deploy-web.yml  # Template reference
    parameters:
      deploymentName: DeployTest
      webAppServiceConnection: '$(webAppServiceConnection)'
      containerRegistry: '$(containerRegistry)'
      imageRepository: '$(imageRepository)'
      tag: '$(tag)'
      webAppName: '${{ variables.deployEnvironmentName }}'
      environmentName: '${{ variables.deployEnvironmentName }}'

- stage: LoadTestStage
  displayName: Load test deployment
  dependsOn: TestStage

  variables:
    deployEnvironmentName: '$(webAppNameBase)-LoadTest'

  jobs:
  - template: jobs/deploy-web.yml  # Template reference
    parameters:
      deploymentName: DeployTest
      webAppServiceConnection: '$(webAppServiceConnection)'
      containerRegistry: '$(containerRegistry)'
      imageRepository: '$(imageRepository)'
      tag: '$(tag)'
      webAppName: '${{ variables.deployEnvironmentName }}'
      environmentName: '${{ variables.deployEnvironmentName }}'

- stage: UATStage
  displayName: UAT deployment
  dependsOn: TestStage

  variables:
    deployEnvironmentName: '$(webAppNameBase)-UAT'

  jobs:
  - template: jobs/deploy-web.yml  # Template reference
    parameters:
      deploymentName: DeployTest
      webAppServiceConnection: '$(webAppServiceConnection)'
      containerRegistry: '$(containerRegistry)'
      imageRepository: '$(imageRepository)'
      tag: '$(tag)'
      webAppName: '${{ variables.deployEnvironmentName }}'
      environmentName: '${{ variables.deployEnvironmentName }}'      

- stage: ProdStage
  displayName: Prod deployment
  dependsOn: LoadTestStage

  variables:
    deployEnvironmentName: '$(webAppNameBase)-Prod'

  jobs:
  - template: jobs/deploy-web.yml  # Template reference
    parameters:
      deploymentName: DeployProd
      webAppServiceConnection: '$(webAppServiceConnection)'
      containerRegistry: '$(containerRegistry)'
      imageRepository: '$(imageRepository)'
      tag: '$(tag)'
      webAppName: '${{ variables.deployEnvironmentName }}'
      environmentName: '${{ variables.deployEnvironmentName }}'     