# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  webAppNameBase: 'ContainerOpsWebApp'
  webAppServiceConnection: '063b33df-431e-4e82-807c-905e5e2f0e0e'
  dockerRegistryServiceConnection: '063b33df-431e-4e82-807c-905e5e2f0e0e'
  containerRegistry: 'slambcontainerregistry.azurecr.io'
  imageRepository: 'containerops'  
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'slambcontainerregistry8ba4-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Name of the new namespace being created to deploy the PR changes.
  k8sNamespaceForPR: 'review-app-$(System.PullRequest.PullRequestId)'

stages:
- stage: BuildStage
  displayName: Build stage

  jobs:
  - template: jobs/build.yml  # Template reference
    parameters:
      dockerRegistryServiceConnection: '$(dockerRegistryServiceConnection)'
      imageRepository: '$(imageRepository)'
      tag: '$(tag)'
      vmImageName: '$(vmImageName)'

- stage: TestStage
  displayName: Test deployment
  dependsOn: BuildStage

  variables:
    deployEnvironmentName: '$(webAppNameBase)-Test'

  jobs:
  - template: jobs/deploy-web.yml  # Template reference
    parameters:
      deploymentName: DeployTest
      webAppServiceConnection: '$(webAppServiceConnection)'
      containerRegistry: '$(containerRegistry)'
      imageRepository: '$(imageRepository)'
      tag: '$(tag)'
      webAppName: '$(environmentName)'
      environmentName: '$(deployEnvironmentName)'

- stage: LoadTestStage
  displayName: Load test deployment
  dependsOn: TestStage

  variables:
    deployEnvironmentName: '$(webAppNameBase)-LoadTest'

  jobs:
  - template: jobs/deploy-web.yml  # Template reference
    parameters:
      deploymentName: DeployTest
      webAppServiceConnection: '$(webAppServiceConnection)'
      containerRegistry: '$(containerRegistry)'
      imageRepository: '$(imageRepository)'
      tag: '$(tag)'
      webAppName: '$(environmentName)'
      environmentName: '$(deployEnvironmentName)'

- stage: UATStage
  displayName: UAT deployment
  dependsOn: TestStage

  variables:
    deployEnvironmentName: '$(webAppNameBase)-UAT'

  jobs:
  - template: jobs/deploy-web.yml  # Template reference
    parameters:
      deploymentName: DeployTest
      webAppServiceConnection: '$(webAppServiceConnection)'
      containerRegistry: '$(containerRegistry)'
      imageRepository: '$(imageRepository)'
      tag: '$(tag)'
      webAppName: '$(environmentName)'
      environmentName: '$(deployEnvironmentName)'      

- stage: ProdStage
  displayName: Prod deployment
  dependsOn: LoadTestStage

  variables:
    deployEnvironmentName: '$(webAppNameBase)-Prod'

  jobs:
  - template: jobs/deploy-web.yml  # Template reference
    parameters:
      deploymentName: DeployProd
      webAppServiceConnection: '$(webAppServiceConnection)'
      containerRegistry: '$(containerRegistry)'
      imageRepository: '$(imageRepository)'
      tag: '$(tag)'
      webAppName: '$(environmentName)'
      environmentName: '$(deployEnvironmentName)'     