parameters:
- name: dockerRegistryServiceConnection
  type: string
- name: imageRepository
  type: string
- name: containerRegistry
  type: string
- name: dockerfilePath
  type: string
- name: imagePullSecret
  type: string
- name: tag
  type: string
  default: '$(Build.BuildId)'
- name: vmImageName
  type: string
  default: 'ubuntu-latest'
- name: k8sNamespaceForPR
  type: string  
  default: 'review-app-$(System.PullRequest.PullRequestId)'

jobs:
- deployment: Deploy
  condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/pull/')))
  displayName: Deploy
  pool:
    vmImage: $(vmImageName)
  environment: 'slamb2kContainerOps-k8s.default'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: KubernetesManifest@0
          displayName: Create imagePullSecret
          inputs:
            action: createSecret
            secretName: ${{ parameters.imagePullSecret }}
            dockerRegistryEndpoint: ${{ parameters.dockerRegistryServiceConnection }}

        - task: KubernetesManifest@0
          displayName: Deploy to Kubernetes cluster
          inputs:
            action: deploy
            manifests: |
              $(Pipeline.Workspace)/manifests/deployment.yml
              $(Pipeline.Workspace)/manifests/service.yml
            imagePullSecrets: |
              ${{ parameters.imagePullSecret }}
            containers: |
              ${{ parameters.containerRegistry }}/${{ parameters.imageRepository }}:$(tag)

